export const ActionTypes = {
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM'
}